import { components, paths } from "@lib/api/owaru"; // <- generated by openapi-typescript

export const API = {
  //URL: "Back IP",
  URL: "http://localhost:8000",
  AUTH: {
    LOGIN: "login/access-token",
    PROFILE: "users/me",
    LOGOUT: "logout",
  },
 };


 export const APP_ROUTES = {
  LOGIN: "/login",
 };