/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 *
 * * Generated by runing: $ npx openapi-typescript "http://localhost:8000/api/schema/" --output schemas/owaru
 */




export interface paths {
  "/": {
      parameters: {
          query?: never;
          header?: never;
          path?: never;
          cookie?: never;
      };
      get: operations["root_list"];
      put?: never;
      post?: never;
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
  };
  "/add/": {
      parameters: {
          query?: never;
          header?: never;
          path?: never;
          cookie?: never;
      };
      get?: never;
      put?: never;
      post: operations["add_create"];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
  };
  "/api/schema/": {
      parameters: {
          query?: never;
          header?: never;
          path?: never;
          cookie?: never;
      };
      /** @description OpenApi3 schema for this API. Format can be selected via content negotiation.
       *
       *     - YAML: application/vnd.oai.openapi
       *     - JSON: application/vnd.oai.openapi+json */
      get: operations["api_schema_retrieve"];
      put?: never;
      post?: never;
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
  };
  "/api/token/": {
      parameters: {
          query?: never;
          header?: never;
          path?: never;
          cookie?: never;
      };
      get?: never;
      put?: never;
      /** @description Takes a set of user credentials and returns an access and refresh JSON web
       *     token pair to prove the authentication of those credentials. */
      post: operations["api_token_create"];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
  };
  "/api/token/refresh/": {
      parameters: {
          query?: never;
          header?: never;
          path?: never;
          cookie?: never;
      };
      get?: never;
      put?: never;
      /** @description Takes a refresh type JSON web token and returns an access type JSON web
       *     token if the refresh token is valid. */
      post: operations["api_token_refresh_create"];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
  };
  "/bunnies/": {
      parameters: {
          query?: never;
          header?: never;
          path?: never;
          cookie?: never;
      };
      get?: never;
      put?: never;
      /** @description Endpoint que ejecuta un modelo y devuelve una matriz de resultados según el parámetro 'Birth Rate'. */
      post: operations["getBunnies"];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
  };
  "/test/": {
      parameters: {
          query?: never;
          header?: never;
          path?: never;
          cookie?: never;
      };
      get?: never;
      put?: never;
      /** @description Endpoint de ejemplo que devuelve un mensaje de saludo */
      post: operations["helloWorld"];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
      CustomTokenObtainPair: {
          email: string;
          password: string;
      };
      Item: {
          readonly id: number;
          name: string;
          /** Format: date-time */
          readonly created: string;
      };
      TokenRefresh: {
          readonly access: string;
          refresh: string;
      };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  root_list: {
      parameters: {
          query?: never;
          header?: never;
          path?: never;
          cookie?: never;
      };
      requestBody?: never;
      responses: {
          200: {
              headers: {
                  [name: string]: unknown;
              };
              content: {
                  "application/json": components["schemas"]["Item"][];
              };
          };
      };
  };
  add_create: {
      parameters: {
          query?: never;
          header?: never;
          path?: never;
          cookie?: never;
      };
      requestBody: {
          content: {
              "application/json": components["schemas"]["Item"];
              "application/x-www-form-urlencoded": components["schemas"]["Item"];
              "multipart/form-data": components["schemas"]["Item"];
          };
      };
      responses: {
          200: {
              headers: {
                  [name: string]: unknown;
              };
              content: {
                  "application/json": components["schemas"]["Item"];
              };
          };
      };
  };
  api_schema_retrieve: {
      parameters: {
          query?: {
              format?: "json" | "yaml";
              lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
          };
          header?: never;
          path?: never;
          cookie?: never;
      };
      requestBody?: never;
      responses: {
          200: {
              headers: {
                  [name: string]: unknown;
              };
              content: {
                  "application/vnd.oai.openapi": {
                      [key: string]: unknown;
                  };
                  "application/yaml": {
                      [key: string]: unknown;
                  };
                  "application/vnd.oai.openapi+json": {
                      [key: string]: unknown;
                  };
                  "application/json": {
                      [key: string]: unknown;
                  };
              };
          };
      };
  };
  api_token_create: {
      parameters: {
          query?: never;
          header?: never;
          path?: never;
          cookie?: never;
      };
      requestBody: {
          content: {
              "application/json": components["schemas"]["CustomTokenObtainPair"];
              "application/x-www-form-urlencoded": components["schemas"]["CustomTokenObtainPair"];
              "multipart/form-data": components["schemas"]["CustomTokenObtainPair"];
          };
      };
      responses: {
          200: {
              headers: {
                  [name: string]: unknown;
              };
              content: {
                  "application/json": components["schemas"]["CustomTokenObtainPair"];
              };
          };
      };
  };
  api_token_refresh_create: {
      parameters: {
          query?: never;
          header?: never;
          path?: never;
          cookie?: never;
      };
      requestBody: {
          content: {
              "application/json": components["schemas"]["TokenRefresh"];
              "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
              "multipart/form-data": components["schemas"]["TokenRefresh"];
          };
      };
      responses: {
          200: {
              headers: {
                  [name: string]: unknown;
              };
              content: {
                  "application/json": components["schemas"]["TokenRefresh"];
              };
          };
      };
  };
  getBunnies: {
      parameters: {
          query?: never;
          header?: never;
          path?: never;
          cookie?: never;
      };
      requestBody?: {
          content: {
              "application/json": {
                  /**
                   * @description Tasa de nacimiento
                   * @example 1.5
                   */
                  "Birth Rate": number;
              };
          };
      };
      responses: {
          200: {
              headers: {
                  [name: string]: unknown;
              };
              content: {
                  "application/json": {
                      /** @description Datos de población */
                      Population?: number[];
                      /** @description Fechas de la simulación */
                      index?: string[];
                  };
              };
          };
          400: {
              headers: {
                  [name: string]: unknown;
              };
              content: {
                  "application/json": {
                      /** @example Birth Rate parameter is required */
                      error?: string;
                  };
              };
          };
      };
  };
  helloWorld: {
      parameters: {
          query?: never;
          header?: never;
          path?: never;
          cookie?: never;
      };
      requestBody?: never;
      responses: {
          200: {
              headers: {
                  [name: string]: unknown;
              };
              content: {
                  "application/json": {
                      /** @description saludo */
                      message?: string;
                  };
              };
          };
      };
  };
}
