import { components, paths } from "@lib/api/owaru"; // <- generated by openapi-typescript

type API_ValidationError = components["schemas"]["ValidationError"];

export type ErrorResponse = {
  detail: string | API_ValidationError[];
};

export type ErrorDetail = {
  loc: Array<number | string>;
  msg: string;
  type: string;
} & API_ValidationError;

export type ErrorObj = {
  error?: string;
  message?: string;
  code?: number;

  api_error?: API_ValidationError[];
};
